#!/usr/bin/env bash
# Conspiracy mesh network daemon installation script
# Usage: sudo bash install.sh [--test-mode]

set -euo pipefail

# Configuration
CONFIG_DIR="/etc/conspiracyd"
CONFIG_FILE="${CONFIG_DIR}/config.toml"
STATE_DIR="/var/lib/conspiracyd"
BINARY_SRC="./bin/conspiracyd"
BINARY_DEST="/usr/sbin/conspiracyd"
SYSTEMD_UNIT="./deployments/systemd/conspiracyd.service"
SYSTEMD_DEST="/etc/systemd/system/conspiracyd.service"
TEST_MODE=false

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
for arg in "$@"; do
    case $arg in
        --test-mode)
            TEST_MODE=true
            shift
            ;;
        *)
            echo "Unknown option: $arg"
            echo "Usage: $0 [--test-mode]"
            exit 1
            ;;
    esac
done

# Helper functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

check_binary() {
    if [[ ! -f "$BINARY_SRC" ]]; then
        log_error "Binary not found at $BINARY_SRC"
        log_info "Build the binary first: go build -o bin/conspiracyd ./cmd/conspiracyd"
        exit 1
    fi
}

check_dependencies() {
    local missing_deps=()
    
    # Check for required commands
    for cmd in openssl systemctl; do
        if ! command -v "$cmd" &> /dev/null; then
            missing_deps+=("$cmd")
        fi
    done
    
    if [[ ${#missing_deps[@]} -gt 0 ]]; then
        log_error "Missing required dependencies: ${missing_deps[*]}"
        log_info "Install them with your package manager (apt, yum, apk, etc.)"
        exit 1
    fi
}

detect_lora_hardware() {
    local device=""
    
    # Check for SPI devices
    if [[ -e /dev/spidev0.0 ]]; then
        device="/dev/spidev0.0"
        log_info "Detected SPI LoRa device: $device"
    elif [[ -e /dev/spidev1.0 ]]; then
        device="/dev/spidev1.0"
        log_info "Detected SPI LoRa device: $device"
    # Check for UART/serial devices
    elif ls /dev/ttyUSB* &> /dev/null; then
        device=$(ls /dev/ttyUSB* | head -n1)
        log_info "Detected USB-Serial LoRa device: $device"
    elif ls /dev/ttyS* &> /dev/null; then
        device=$(ls /dev/ttyS* | grep -v ttyS0 | head -n1)
        log_info "Detected UART LoRa device: $device"
    else
        log_warn "No LoRa hardware detected (SPI/UART/USB)"
        log_warn "Using UDP mode for testing (requires manual config editing)"
        device="udp"
    fi
    
    echo "$device"
}

detect_region() {
    # Simple region detection based on timezone (heuristic)
    local tz
    tz=$(timedatectl show -p Timezone --value 2>/dev/null || echo "UTC")
    
    case "$tz" in
        Europe/*|Africa/*)
            echo "eu868"
            ;;
        America/*|US/*)
            echo "us915"
            ;;
        Asia/*|Australia/*|Pacific/*)
            echo "as923"
            ;;
        *)
            log_warn "Could not detect region from timezone: $tz"
            echo "eu868"  # Default to EU
            ;;
    esac
}

generate_mesh_key() {
    log_info "Generating 256-bit mesh key..."
    openssl rand -hex 32
}

create_config() {
    local lora_device="$1"
    local region="$2"
    local mesh_key="$3"
    
    # Regional frequency settings
    local freq_mhz
    local spreading
    local duty_cycle_comment
    
    case "$region" in
        eu868)
            freq_mhz="868.1"
            spreading="10"
            duty_cycle_comment="# EU: 1% duty cycle = 36s/hour"
            ;;
        us915)
            freq_mhz="915.0"
            spreading="7"
            duty_cycle_comment="# US: 4% duty cycle = 144s/hour"
            ;;
        as923)
            freq_mhz="923.0"
            spreading="9"
            duty_cycle_comment="# Asia: 1% duty cycle = 36s/hour"
            ;;
        *)
            freq_mhz="868.1"
            spreading="10"
            duty_cycle_comment="# EU: 1% duty cycle = 36s/hour"
            ;;
    esac
    
    mkdir -p "$CONFIG_DIR"
    
    cat > "$CONFIG_FILE" <<EOF
# Conspiracy LoRa-Mesh Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Region: $region
$duty_cycle_comment

[lora]
device        = "$lora_device"
frequency_mhz = $freq_mhz
spreading     = $spreading
bandwidth_khz = 125
mesh_key      = "hex:$mesh_key"

[wifi]
mesh_interface = "wlan0"
ssid           = "conspiracy-mesh"
channel        = 6

[batman]
interface      = "bat0"
enabled        = true

[plugins]
yggdrasil = false
cjdns     = false
EOF
    
    chmod 600 "$CONFIG_FILE"
    log_info "Configuration written to $CONFIG_FILE"
}

install_binary() {
    log_info "Installing conspiracyd binary to $BINARY_DEST"
    cp "$BINARY_SRC" "$BINARY_DEST"
    chmod 755 "$BINARY_DEST"
}

install_systemd_unit() {
    if [[ ! -f "$SYSTEMD_UNIT" ]]; then
        log_error "Systemd unit file not found at $SYSTEMD_UNIT"
        exit 1
    fi
    
    log_info "Installing systemd unit to $SYSTEMD_DEST"
    cp "$SYSTEMD_UNIT" "$SYSTEMD_DEST"
    chmod 644 "$SYSTEMD_DEST"
    systemctl daemon-reload
}

create_state_directory() {
    log_info "Creating state directory $STATE_DIR"
    mkdir -p "$STATE_DIR"
    chmod 700 "$STATE_DIR"
    
    # Create canary file to test write permissions
    if ! touch "$STATE_DIR/.canary" 2>/dev/null; then
        log_error "Cannot write to $STATE_DIR (required for reboot counter persistence)"
        exit 1
    fi
    rm -f "$STATE_DIR/.canary"
}

enable_and_start_service() {
    if [[ "$TEST_MODE" == "true" ]]; then
        log_warn "Test mode: Skipping service enable/start"
        return
    fi
    
    log_info "Enabling and starting conspiracyd service"
    systemctl enable conspiracyd
    systemctl start conspiracyd
    
    # Wait for service to start
    sleep 2
    
    if systemctl is-active --quiet conspiracyd; then
        log_info "Service started successfully"
        systemctl status conspiracyd --no-pager --lines=5
    else
        log_error "Service failed to start. Check logs: journalctl -u conspiracyd -n 50"
        exit 1
    fi
}

print_next_steps() {
    cat <<EOF

${GREEN}Installation complete!${NC}

Configuration file: $CONFIG_FILE
Binary location:    $BINARY_DEST
Service status:     systemctl status conspiracyd
View logs:          journalctl -u conspiracyd -f

${YELLOW}IMPORTANT:${NC}
1. Review and customize $CONFIG_FILE for your deployment
2. Change the mesh_key if joining an existing network
3. Ensure LoRa hardware is properly connected
4. Check Wi-Fi interface name (default: wlan0)

${YELLOW}Next steps:${NC}
- View daemon logs:     journalctl -u conspiracyd -f
- Stop the daemon:      systemctl stop conspiracyd
- Restart the daemon:   systemctl restart conspiracyd
- Check metrics:        curl http://localhost:9090/metrics

For troubleshooting and documentation:
https://github.com/opd-ai/conspiracy
EOF
}

# Main installation flow
main() {
    log_info "Starting Conspiracy mesh network daemon installation"
    
    check_root
    check_dependencies
    check_binary
    
    # Detect hardware and region
    local lora_device
    local region
    local mesh_key
    
    lora_device=$(detect_lora_hardware)
    region=$(detect_region)
    mesh_key=$(generate_mesh_key)
    
    log_info "Detected region: $region"
    
    # Create configuration
    create_config "$lora_device" "$region" "$mesh_key"
    
    # Install components
    install_binary
    install_systemd_unit
    create_state_directory
    
    # Enable and start service
    enable_and_start_service
    
    print_next_steps
}

# Run main function
main
